apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejscontainerapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejscontainerapp
  template:
    metadata:
      labels:
        app: nodejscontainerapp
    spec:
      containers:
      - name: nodejscontainerapp
        image: polzer/nodejscontainerapp:v01
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nodejscontainerapp-service
spec:
  selector:
    app: nodejscontainerapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    name: instance
    targetPort: 3000
    nodePort: 30008


